"""Generates jctool/tables.py from CTCaer's C headers (jctool/luts.h, ir_sensor.h, tune.h).

    python3 tools/gen_tables.py      (from the python/ directory)
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "..", "jctool")
OUT = os.path.join(HERE, "..", "jctool", "tables.py")


def numbers(text):
    """The numbers of a C initializer, in order (hex, decimal and float literals)."""
    text = re.sub(r"//[^\n]*", "", text)
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    out = []
    for tok in re.findall(r"0[xX][0-9a-fA-F]+|\d+\.\d*f?|\.\d+f?|\d+", text):
        if tok.lower().startswith("0x"):
            out.append(int(tok, 16))
        elif "." in tok:
            out.append(float(tok.rstrip("fF")))
        else:
            out.append(int(tok))
    return out


def array(source, name):
    m = re.search(r"\b" + re.escape(name) + r"\s*\[[^\]]*\]\s*=\s*\{(.*?)\};", source, re.S)
    if not m:
        raise SystemExit("array not found: " + name)
    return numbers(m.group(1))


def wrap(values, per_line, fmt):
    lines = []
    for i in range(0, len(values), per_line):
        lines.append("    " + ", ".join(fmt(v) for v in values[i:i + per_line]) + ",")
    return "\n".join(lines)


def main():
    luts = open(os.path.join(SRC, "luts.h")).read()
    body = re.search(r"lut_joy_amp\s*\{(.*)\};", luts, re.S).group(1)
    groups = re.findall(r"\{(.*?)\}", body, re.S)
    amp_float, amp_ha, amp_la = (numbers(g) for g in groups[:3])
    assert len(amp_float) == len(amp_ha) == len(amp_la) == 101, (len(amp_float), len(amp_ha), len(amp_la))

    ir = open(os.path.join(SRC, "ir_sensor.h")).read()
    crc8 = array(ir, "mcu_crc8_table")
    iron = array(ir, "iron_palette")
    assert len(crc8) == 256 and len(iron) == 256

    tune = open(os.path.join(SRC, "tune.h")).read()
    smb = array(tune, "tune_SMB")
    smo = array(tune, "tune_SMO_OK")
    assert len(smb) == 2740 and len(smo) == 4941

    with open(OUT, "w") as f:
        f.write('"""Lookup tables from CTCaer\'s Joy-Con Toolkit (luts.h, ir_sensor.h, tune.h).\n\n'
                'Generated by tools/gen_tables.py. Copyright (c) 2018 CTCaer, MIT license."""\n\n')
        f.write("# HD Rumble amplitude encoding: float amplitude, high band byte, low band word\n")
        f.write("AMP_FLOAT = (\n" + wrap(amp_float, 8, lambda v: repr(float(v))) + "\n)\n\n")
        f.write("AMP_HA = (\n" + wrap(amp_ha, 16, lambda v: "0x%02X" % v) + "\n)\n\n")
        f.write("AMP_LA = (\n" + wrap(amp_la, 12, lambda v: "0x%04X" % v) + "\n)\n\n")
        f.write("MCU_CRC8 = (\n" + wrap(crc8, 16, lambda v: "0x%02X" % v) + "\n)\n\n")
        f.write("# IR camera Ironbow palette, 0xRRGGBB\n")
        f.write("IRON_PALETTE = (\n" + wrap(iron, 8, lambda v: "0x%06X" % v) + "\n)\n\n")
        f.write("# Easter egg tunes: one 4-byte rumble sample (big endian) every 15ms\n")
        f.write("TUNE_SMB = (\n" + wrap(smb, 8, lambda v: "0x%08X" % v) + "\n)\n\n")
        f.write("TUNE_SMO_OK = (\n" + wrap(smo, 8, lambda v: "0x%08X" % v) + "\n)\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
