#!/usr/bin/env python3
# Copyright (c) 2018 CTCaer. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.
"""Convert the WinForms designer part of jctool/FormJoy.h (C++/CLI) to C#.

Writes:
  FormJoy.Designer.cs   partial class FormJoy: control fields + InitializeComponent()
  FormJoy.Handlers.cs   one stub per event handler the designer wires up, with
                        the right EventArgs type. Each stub only logs that it
                        is not ported yet, so the form runs while you port.
                        Move each one into FormJoy.cs with the body ported
                        from FormJoy.h's "Functions" section.

Usage: cppcli_designer_to_cs.py jctool/FormJoy.h OUTDIR
"""

import os
import re
import sys

VALUE_TYPES = r"System::Drawing::(?:Point|Size|SizeF|Rectangle)|System::Windows::Forms::Padding|System::Decimal"


def convert(code):
    # Adjacent C++ string literals on consecutive lines -> C# concatenation
    code = re.sub(r'"(\s*\n\s*)L"', r'" +\1"', code)
    code = re.sub(r'(?<![\w"])L(["\'])', r"\1", code)

    code = re.sub(r"static_cast<System::Int32>\(static_cast<System::Byte>\((\d+)\)\)", r"\1", code)
    code = re.sub(r"cli::safe_cast<([^<>]+?)\^\s*>\(", r"(\1)(", code)
    code = re.sub(r"static_cast<([^<>]+?)>\(", r"(\1)(", code)
    code = re.sub(r"gcnew\s+cli::array<\s*([^<>]+?)\^?\s*>\(\d+\)", r"new \1[]", code)
    code = re.sub(r"\bgcnew\b", "new", code)
    code = re.sub(r"(?<!new )(?<![\w:])(" + VALUE_TYPES + r")\(", r"new \1(", code)
    code = re.sub(r"\(this,\s*&FormJoy::(\w+)\)", r"(this.\1)", code)
    code = re.sub(r"(\w+)::typeid", r"typeof(\1)", code)
    code = re.sub(r"\^(?=[\s>)\]])", "", code)
    code = code.replace("this->", "this.").replace("->", ".").replace("::", ".")
    code = re.sub(r"\bnullptr\b", "null", code)
    code = re.sub(r"^(\s*)(private|public|protected):\s*", r"\1\2 ", code, flags=re.M)
    return code


def main():
    src, outdir = sys.argv[1], sys.argv[2]
    text = open(src, encoding="utf-8", errors="replace").read()

    fields = re.search(r"#pragma region Class Variables\n(.*?)#pragma endregion", text, re.S).group(1)
    designer = re.search(r"#pragma region Windows Form Designer generated code\n(.*?)#pragma endregion", text, re.S).group(1)

    # Only the control fields belong to the designer file; the remaining class
    # variables (state, colors, buffers) move to FormJoy.cs with the logic.
    field_lines = [l for l in fields.splitlines()
                   if re.match(r"\s*(private|public):\s*System::(Windows::Forms|ComponentModel)::\w+\^\s+\w+;", l)]

    designer = designer.replace("void InitializeComponent(void)", "private void InitializeComponent()")

    out = ["// Generated by linux/mono/tools/cppcli_designer_to_cs.py from jctool/FormJoy.h.",
           "// Re-run the script after changing the form in FormJoy.h instead of editing this file.",
           "",
           "namespace CppWinFormJoy",
           "{",
           "    partial class FormJoy",
           "    {",
           convert("\n".join(field_lines)),
           "",
           convert(designer).rstrip(),
           "    }",
           "}",
           ""]
    os.makedirs(outdir, exist_ok=True)
    with open(os.path.join(outdir, "FormJoy.Designer.cs"), "w", encoding="utf-8") as f:
        f.write("\n".join(out))

    handlers = {}
    for delegate, name in re.findall(r"gcnew\s+([\w:]*EventHandler)\(this,\s*&FormJoy::(\w+)\)", designer):
        args = delegate.split("::")[-1].replace("EventHandler", "EventArgs") or "EventArgs"
        ns = "System.ComponentModel" if args == "CancelEventArgs" else \
             "System" if args == "EventArgs" else "System.Windows.Forms"
        handlers.setdefault(name, "%s.%s" % (ns, args))

    stubs = ["// Generated by linux/mono/tools/cppcli_designer_to_cs.py: event handlers wired up in",
             "// InitializeComponent(). Port each body from the matching function in jctool/FormJoy.h.",
             "",
             "namespace CppWinFormJoy",
             "{",
             "    partial class FormJoy",
             "    {"]
    for name, args in sorted(handlers.items()):
        stubs.append("        private void %s(object sender, %s e) { System.Console.Error.WriteLine(\"Not ported yet: %s\"); }"
                     % (name, args, name))
    stubs += ["    }", "}", ""]
    with open(os.path.join(outdir, "FormJoy.Handlers.cs"), "w", encoding="utf-8") as f:
        f.write("\n".join(stubs))

    print("%d control fields, %d designer lines, %d event handlers"
          % (len(field_lines), designer.count("\n"), len(handlers)))


if __name__ == "__main__":
    main()
