#!/usr/bin/env python3
# Copyright (c) 2018 CTCaer. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.
"""Generate src/Tables.cs from jctool's tune.h, ir_sensor.h and luts.h.

Usage: gen_tables.py jctool/ OUT.cs
Arrays keep their declared C sizes (missing initializers are zero, as in C).
"""

import os
import re
import sys


def values(text):
    text = re.sub(r"//.*", "", text)
    return re.findall(r"0x[0-9a-fA-F]+|\d+\.\d+f?|\b\d+\b", text)


def array(src, name):
    m = re.search(name + r"\[(\d*)\]\s*=\s*\{(.*?)\};", src, re.S)
    vals = values(m.group(2))
    size = int(m.group(1)) if m.group(1) else len(vals)
    return vals + ["0"] * (size - len(vals))


def emit(ctype, name, vals, per_line=8):
    lines = ["        public static readonly %s[] %s = new %s[%d] {" % (ctype, name, ctype, len(vals))]
    for i in range(0, len(vals), per_line):
        lines.append("            " + ", ".join(vals[i:i + per_line]) + ",")
    lines.append("        };")
    return "\n".join(lines)


def main():
    srcdir, out = sys.argv[1], sys.argv[2]
    tune = open(os.path.join(srcdir, "tune.h")).read()
    ir = open(os.path.join(srcdir, "ir_sensor.h")).read()
    luts = open(os.path.join(srcdir, "luts.h")).read()

    m = re.search(r"lut_joy_amp\s*\{(.*)\};", luts, re.S)
    groups = re.findall(r"\{([^{}]*)\}", m.group(1))
    amp_float = [v if v.endswith("f") else v + "f" for v in values(groups[0])]

    parts = [
        "// Generated by linux/mono/tools/gen_tables.py from jctool/tune.h, ir_sensor.h and luts.h.",
        "",
        "namespace CppWinFormJoy",
        "{",
        "    public static class Tables",
        "    {",
        emit("byte", "mcu_crc8_table", array(ir, "mcu_crc8_table"), 16),
        "",
        "        // ARGB Ironbow palette",
        emit("uint", "iron_palette", array(ir, "iron_palette")),
        "",
        "        // lut_joy_amp",
        emit("float", "lut_amp_float", amp_float),
        emit("byte", "lut_amp_ha", values(groups[1])),
        emit("ushort", "lut_amp_la", values(groups[2])),
        "",
        "        // Super Mario Bros - Main theme",
        emit("uint", "tune_SMB", array(tune, "tune_SMB")),
        "",
        emit("uint", "tune_SMO_OK", array(tune, "tune_SMO_OK")),
        "    }",
        "}",
        "",
    ]
    open(out, "w").write("\n".join(parts))


if __name__ == "__main__":
    main()
